MODEL:
  META_ARCHITECTURE: "CondInst"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    THRESH_WITH_CTR: True
    USE_SCALE: True
  CONDINST:
    MAX_PROPOSALS: 500
DATASETS:
  TRAIN: ("voc_2012_gaze_train",)
  TEST: ("voc_2012_gaze_val",)
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.01
  STEPS: (15000,)
  MAX_ITER: 20000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MASK_FORMAT: bitmask
